allowBuilds:
  esbuild: true
  lightningcss: true
  msw: true
  sharp: true
  msgpackr-extract: false
  workerd: true
minimumReleaseAge: 0
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vitest: 4.1.10
  vite-plus: 0.2.5
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
