/* eslint-disable */
// Generated by Alchemy — run `alchemy deploy` to provision.
// Re-export from alchemy.run.ts for typed Worker env bindings.

import type { WebsiteEnv } from "./alchemy.run";

declare namespace Cloudflare {
  interface Env extends WebsiteEnv {}
}

interface Env extends Cloudflare.Env {}

declare namespace NodeJS {
  interface ProcessEnv extends WebsiteEnv {}
}
