#import "@preview/basic-resume:0.2.9": *

#let accent-color = "#861043"
#let body-font = "Libertinus Serif"
#let paper = "us-letter"
#let font-size = 10pt
#let author-font-size = 20pt

#show heading.where(level: 2): set block(above: 1em, below: 0.5em)

// Generated by `pnpm gen:cv` from src/data and src/content/projects.
// This file is layout only. Every value below is already display-ready.
#let cv = json("data.json")

#let months = (
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
)

// "2026-01" -> "Jan 2026"
#let month-year(value) = {
  let parts = value.split("-")
  months.at(int(parts.at(1)) - 1) + " " + parts.at(0)
}

// An open-ended period reads "Present"; a closed one spells out its own end.
#let period(entry) = dates-helper(
  start-date: month-year(entry.period.at(0)),
  end-date: if entry.period.at(1) == none {
    "Present"
  } else {
    month-year(entry.period.at(1))
  },
)

#let stack(entry) = entry.stack.join(", ")

#show: resume.with(
  author: cv.profile.name,
  location: cv.profile.location,
  email: cv.profile.email,
  github: cv.profile.github,
  linkedin: cv.profile.linkedin,
  personal-site: cv.profile.personalSite,
  accent-color: accent-color,
  font: body-font,
  paper: paper,
  font-size: font-size,
  author-font-size: author-font-size,
  author-position: left,
  personal-info-position: left,
)

== Work Experience

// The gap goes above each entry rather than below it. A trailing gap after the
// last entry of a section is what tips the next heading onto a new page, and
// this CV only just fits on one.
#for (i, entry) in cv.work.enumerate() [
  #if i > 0 [#parbreak()]
  #work(
    title: entry.position,
    dates: period(entry),
    company: entry.company + " - " + entry.engagement,
    location: entry.location,
  )
  #for detail in entry.details [
    - #detail
  ]
  #strong[Stack:] #stack(entry)
]

== Projects

#for (i, entry) in cv.projects.enumerate() [
  #if i > 0 [#parbreak()]
  #project(name: entry.name, url: entry.url, dates: period(entry))
  #for detail in entry.details [
    - #detail
  ]
  #parbreak()
  #strong[Stack:] #stack(entry)
]

== Education

#for school in cv.education [
  #edu(
    institution: school.institution,
    location: school.location,
    degree: school.degree,
    dates: period(school),
  )
  #for detail in school.details [
    - #detail
  ]
  #parbreak()
]