/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as ApiOgImageRouteImport } from './routes/api.og-image'
import { Route as ApiGraphJsonRouteImport } from './routes/api.graph-json'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgImageRoute = ApiOgImageRouteImport.update({
  id: '/api/og-image',
  path: '/api/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphJsonRoute = ApiGraphJsonRouteImport.update({
  id: '/api/graph-json',
  path: '/api/graph-json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/notes': typeof NotesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/notes/'
    | '/posts/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/notes'
    | '/posts'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/notes/'
    | '/posts/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGraphJsonRoute: typeof ApiGraphJsonRoute
  ApiOgImageRoute: typeof ApiOgImageRoute
  NotesSlugRoute: typeof NotesSlugRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og-image': {
      id: '/api/og-image'
      path: '/api/og-image'
      fullPath: '/api/og-image'
      preLoaderRoute: typeof ApiOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph-json': {
      id: '/api/graph-json'
      path: '/api/graph-json'
      fullPath: '/api/graph-json'
      preLoaderRoute: typeof ApiGraphJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGraphJsonRoute: ApiGraphJsonRoute,
  ApiOgImageRoute: ApiOgImageRoute,
  NotesSlugRoute: NotesSlugRoute,
  PostsSlugRoute: PostsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  NotesIndexRoute: NotesIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
