/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as ApiOgImageRouteImport } from './routes/api.og-image'
import { Route as ApiGraphJsonRouteImport } from './routes/api.graph-json'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotesRoute,
} as any)
const ApiOgImageRoute = ApiOgImageRouteImport.update({
  id: '/api/og-image',
  path: '/api/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphJsonRoute = ApiGraphJsonRouteImport.update({
  id: '/api/graph-json',
  path: '/api/graph-json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/api/graph-json': typeof ApiGraphJsonRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/posts'
    | '/projects'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/posts'
    | '/projects'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/posts'
    | '/projects'
    | '/api/graph-json'
    | '/api/og-image'
    | '/notes/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ApiGraphJsonRoute: typeof ApiGraphJsonRoute
  ApiOgImageRoute: typeof ApiOgImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof NotesRoute
    }
    '/api/og-image': {
      id: '/api/og-image'
      path: '/api/og-image'
      fullPath: '/api/og-image'
      preLoaderRoute: typeof ApiOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph-json': {
      id: '/api/graph-json'
      path: '/api/graph-json'
      fullPath: '/api/graph-json'
      preLoaderRoute: typeof ApiGraphJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotesRouteChildren {
  NotesSlugRoute: typeof NotesSlugRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSlugRoute: NotesSlugRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ApiGraphJsonRoute: ApiGraphJsonRoute,
  ApiOgImageRoute: ApiOgImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
